### ISSUE TITLE
Privileged container spc_t optional

### ISSUE THREAD

**Issue by patsys** [SELinuxProject/refpolicy#753]
Hello,

on my kubernetes I will label all privileged container with a more strict label then spc_t, for this case it must the automatic transition to spc_t optional.

Position: https://github.com/SELinuxProject/refpolicy/blob/9c3fca3bed8f5c4aeba860682ddfd152344d5254/policy/modules/services/container.te#L955-L957C77

issue with CRI-O, trying to make it work with containerd: https://github.com/cri-o/cri-o/issues/5501

**Comment by 0xC0ncord** [comment]
While this is a relatively simple change to implement I'm not sure this would be within the scope of refpolicy as opposed to a custom policy. I think if this were added, I would make the relevant rules tunable and make this tunable enabled by default. Disabling this tunable would effectively break all privileged containers though until you implement your own transition rules.

This got me curious though, as I would imagine it should be possible to deploy a workload like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-selinux
  labels:
    environment: test
spec:
  selector:
    matchLabels:
      environment: test
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - /bin/sleep
          args:
            - infinity
          securityContext:
            privileged: true
            seLinuxOptions:
              type: container_t
```
Note the presence of `privileged: true` and the manually specified SELinux type. Unfortunately this still creates a container running as `spc_t` in my testing (at least with CRI-O 1.26.0) which is unfortunate.
